// @generated by protoc-gen-connect-web v0.3.3 with parameter "target=ts"
// @generated from file htmlservice.proto (package grpcservices, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { HTMLResponse } from "./htmlservice_pb";

/**
 * @generated from service grpcservices.HTMLService
 */
export const HTMLService = {
  typeName: "grpcservices.HTMLService",
  methods: {
    /**
     * @generated from rpc grpcservices.HTMLService.GetIndex
     */
    getIndex: {
      name: "GetIndex",
      I: Empty,
      O: HTMLResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

